auto: true
markdown: rdiscount
paginate: 10
paginate_path: "/blog/page:num/"
# permalink: /:year/:month/:title
rdiscount extensions: [smart]
gems:
#  - octopress-paginate
  - jekyll-paginate

permalink: /:categories/:title/
