auto: true
markdown: rdiscount
paginate: 10
paginate_path: "/page:num/"
# permalink: /:year/:month/:title
rdiscount extensions: [smart]
gems: [jekyll-paginate]
permalink: /:categories/:title/
url: http://sylviang.github.io/
