auto: true
markdown: rdiscount
#paginate: 10
#paginate_path: "/page:num/"
# permalink: /:year/:month/:title
rdiscount extensions: [smart]
gems: [jekyll-paginate-v2]
#  - octopress-paginate
#  - jekyll-paginate

permalink: /:categories/:title/
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
